# Generated by Django 4.0.6 on 2022-08-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_orders_address_alter_orders_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dishes',
            field=models.ManyToManyField(null=True, to='rest_api.dish'),
        ),
    ]
